use crate::api::*;
use crate::hoops::auth_hoop;
use salvo::prelude::*;

pub fn root() -> Router {
    let router = Router::new().append(&mut create_router());
    let doc = OpenApi::new("im-server web api", "0.0.1").merge_router(&router);
    router
        .unshift(doc.into_router("/api-doc/openapi.json"))
        .unshift(Scalar::new("/api-doc/openapi.json").into_router("scalar"))
}

pub fn create_router() -> Vec<Router> {
    let v1 = Router::with_path("api/v1")
        .push(Router::with_path("upload").post(upload_api::upload_file))
        .push(Router::with_path("download/{open_id}/{*+file_name}").get(upload_api::get_file))
        .push(
            Router::with_path("auth")
                .push(Router::with_path("login").post(auth_api::post_login))
                .push(Router::with_path("register").post(auth_api::register)),
        )
        .push(
            Router::with_path("subscriptions/{subscription_id}/user")
                .get(subcription_api::get_user_id_by_subscription),
        )
        .push(
            Router::with_path("messages")
                .get(message_api::get_messages)
                .post(message_api::send_message),
        )
        .push(
            Router::with_path("users")
                .hoop(auth_hoop)
                .post(user_api::create_user)
                .get(user_api::list_users)
                .put(user_api::update_current_user)
                .push(Router::with_path("{id}").get(user_api::get_user)),
        )
        .push(
            Router::with_path("friends")
                .hoop(auth_hoop)
                .get(friend_api::get_friends)
                .push(
                    Router::with_path("{id}")
                        .post(friend_api::add_friend)
                        .delete(friend_api::remove_friend),
                ),
        )
        .push(
            Router::with_path("im")
                .push(
                    Router::with_path("users")
                        .post(im_user_api::create_user)
                        .push(
                            Router::with_path("{user_id}")
                                .get(im_user_api::get_user)
                                .push(
                                    Router::with_path("data")
                                        .hoop(auth_hoop)
                                        .get(im_user_api::get_user_data)
                                        .put(im_user_api::upsert_user_data),
                                ),
                        ),
                )
                .push(Router::with_path("auth").post(im_user_api::login))
                .push(
                    Router::with_path("friendships/{open_id}/friends")
                        .get(im_friendship_api::get_friends_by_open_id),
                )
                .push(
                    Router::with_path("friends")
                        .hoop(auth_hoop)
                        .get(im_friendship_api::get_friends)
                        .post(im_friendship_api::add_friend)
                        .push(
                            Router::with_path("{to_id}")
                                .delete(im_friendship_api::remove_friend)
                                .push(
                                    Router::with_path("remark")
                                        .put(im_friendship_api::update_remark),
                                )
                                .push(
                                    Router::with_path("black")
                                        .post(im_friendship_api::black_friend),
                                ),
                        ),
                )
                .push(
                    Router::with_path("groups")
                        .hoop(auth_hoop)
                        .get(im_group_api::get_user_groups)
                        .post(im_group_api::create_group)
                        .push(
                            Router::with_path("{group_id}")
                                .get(im_group_api::get_group)
                                .put(im_group_api::update_group)
                                .push(
                                    Router::with_path("members")
                                        .get(im_group_api::get_group_members)
                                        .push(
                                            Router::with_path("{member_id}")
                                                .post(im_group_api::add_group_member)
                                                .delete(im_group_api::remove_group_member)
                                                .push(
                                                    Router::with_path("role")
                                                        .put(im_group_api::update_member_role),
                                                )
                                                .push(
                                                    Router::with_path("alias")
                                                        .put(im_group_api::update_member_alias),
                                                ),
                                        ),
                                )
                                .push(
                                    Router::with_path("dissolve")
                                        .delete(im_group_api::dissolve_group),
                                )
                                .push(
                                    Router::with_path("delete").delete(im_group_api::delete_group),
                                ),
                        ),
                )
                .push(
                    Router::with_path("friendship-requests")
                        .hoop(auth_hoop)
                        .get(im_friendship_api::get_friendship_requests)
                        .post(im_friendship_api::create_friendship_request)
                        .push(
                            Router::with_path("{request_id}")
                                .post(im_friendship_api::handle_friendship_request),
                        ),
                )
                .push(
                    Router::with_path("message")
                        .hoop(auth_hoop)
                        .push(
                            Router::with_path("single")
                                .get(im_message_api::get_single_message)
                                .post(im_message_api::send_single_message)
                                .push(
                                    Router::with_path("{message_id}/read")
                                        .post(im_message_api::mark_single_message_read),
                                ),
                        )
                        .push(
                            Router::with_path("group").push(
                                Router::with_path("{group_id}")
                                    .get(im_message_api::get_group_message)
                                    .push(
                                        Router::with_path("{message_id}/read")
                                            .post(im_message_api::mark_group_message_read),
                                    )
                                    .push(
                                        Router::with_path("{message_id}/status")
                                            .get(im_message_api::get_group_message_status),
                                    )
                                    .push(
                                        Router::with_path("status")
                                            .get(im_message_api::get_user_group_message_status),
                                    ),
                            ),
                        ),
                )
                .push(
                    Router::with_path("outbox")
                        .hoop(auth_hoop)
                        .post(im_outbox_api::create_outbox)
                        .push(Router::with_path("pending").get(im_outbox_api::get_pending_messages))
                        .push(Router::with_path("failed").get(im_outbox_api::get_failed_messages))
                        .push(
                            Router::with_path("{id}")
                                .get(im_outbox_api::get_outbox)
                                .push(
                                    Router::with_path("status")
                                        .put(im_outbox_api::update_outbox_status),
                                )
                                .push(Router::with_path("sent").put(im_outbox_api::mark_sent)),
                        ),
                )
                .push(
                    Router::with_path("chats")
                        .head(auth_hoop)
                        .get(im_chat_api::get_user_chats)
                        .post(im_chat_api::get_or_create_chat)
                        .push(Router::with_path("unread-stats").get(im_chat_api::get_unread_stats))
                        .push(
                            Router::with_path("{chat_id}")
                                .put(im_chat_api::update_chat)
                                .delete(im_chat_api::delete_chat),
                        )
                        .push(
                            Router::with_path("{chat_id}/remark")
                                .put(im_chat_api::update_chat_remark),
                        )
                        .push(
                            Router::with_path("{chat_id}/read-sequence")
                                .put(im_chat_api::update_read_sequence),
                        ),
                ),
        );

    vec![v1]
}
